from src.utils.file_scanner import scan_code_files
from src.agents.code_analyzer import CodeAnalyzer
from src.agents.doc_writer import DocWriter

class Orchestrator:
    def __init__(self):
        self.analyzer = CodeAnalyzer()
        self.writer = DocWriter()

    def run(self, directory: str, output_path: str) -> str:
        files = scan_code_files(directory)
        print(f"📁 Found {len(files)} code files.")
        full_doc = f"# Auto-generated Documentation\n\n*Generated by MiMo-powered Agent*\n\n"
        for file in files:
            print(f"🔍 Analyzing {file}...")
            with open(file, "r", encoding="utf-8", errors="ignore") as f:
                code = f.read()
            analysis = self.analyzer.analyze(str(file), code)
            print(f"✍️  Writing doc for {file}...")
            doc_section = self.writer.write(str(file), analysis)
            full_doc += doc_section + "\n\n---\n\n"
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(full_doc)
        print(f"✅ Documentation saved to {output_path}")
        return output_path